### ISSUE TITLE
Blufi to send the file to ESP32.

### ISSUE THREAD

**Issue by partylover** [EspressifApp/EspBlufiForAndroid#13]
I want Blufi to send files to ESP32. What can I do?

**Comment by XuXiangJun** [comment]
You can call **BlufiClient.postCustomData(byte[] data)** to send data to device.

**Comment by partylover** [comment]
Thank you

**Comment by JDchew** [comment]
Hi, may I know which IDE are you all using to open this project ?

**Comment by XuXiangJun** [comment]
@JDchew 
Android Studio

**Comment by partylover** [comment]
@XuXiangJun I have tested that it cannot send large files. It can only send 0-200 kB.

**Comment by XuXiangJun** [comment]
You should first negotiate a protocol with the device, then send the data in fragments, and every fragment is no more than 1000 bytes.
