### ISSUE TITLE
andorid 6.0 以上连接发现不了服务

### ISSUE THREAD

**Issue by huaxiao47** [EspressifApp/EspBlufiForAndroid#14]
你好！测试在低版本的android连接正常，在小米8和华为mate10等连接大概率发现不了服务，极低概率能发现服务。调用 connect  之后没有反应，没有任何回调过十几秒后断开连接，反回 status=22.

**Comment by ThiagoRabeloFraga** [comment]
What's the solution for this @huaxiao47 ?
