### ISSUE TITLE
Unable to increase MTU size more then 20 bytes

### ISSUE THREAD

**Issue by persan666** [EspressifApp/EspBlufiForAndroid#15]
Hi,
My phone, a Samsung Galaxy S10+ recently updated to Android 10. After that I started to get communication problems. If I use a MTU size larger then 20 bytes the communication stops and get disconnected when the data to be sent is larger then 20 bytes.
I experienced this with a older version of your Android project back in jun. I have updated the project to your latest commit but I experience the same problem.

/Per

**Comment by XuXiangJun** [comment]
We have also discovered this problems on Samsung S10e, please upgrade our APP.
We found if we call BluetoothGatt.requestMTU(int), the bug will be occured, so don't call requestMTU function in your project.
I think this is Samsung's bug, so we can only wait for Samsung to fix it.

**Comment by persan666** [comment]
OK!
We have also seen this on a Huawei P20 with Android 9. This also stopped working after a update was received. So the problem seems to be present on other devices as well.

**Comment by XuXiangJun** [comment]
I have alse tested on Huawei Mate9(Android 9) and P30(Android 10), and it works well.
Can you upload the APP logcat text for me ?
