### ISSUE TITLE
上周按照demo流程配网已成功。但是今天重新给设备配网无法成功！

### ISSUE THREAD

**Issue by tangchuanyong** [EspressifApp/EspBlufiForAndroid#17]
Receive error code -1000

**Comment by tangchuanyong** [comment]
demo运行也是返回这个错误！

**Comment by XuXiangJun** [comment]
请问用的是什么手机什么系统？

**Comment by tangchuanyong** [comment]
刚刚应该是硬件那边的问题,现在可以了！

**Comment by tangchuanyong** [comment]
硬件那边说可能是距离的问题，我想着不应该的！

**Comment by XuXiangJun** [comment]
-1000 是表示 APP 收到的设备消息内容格式不对，APP 这边用 BluFi 协议解析不出来

**Comment by tangchuanyong** [comment]
怎么看返回的消息格式是否正确？

**Comment by tangchuanyong** [comment]
我这边现在运行demo和我的代码又出现这个问题了！我用的是vivo nex手机！

**Comment by tangchuanyong** [comment]
我这边在配网是显示 设备不支持5G wifi，继续配网？是不是这个原因导致的问题！

**Comment by XuXiangJun** [comment]
检查消息格式是我们 BluFi 库下面做的
设备是配不上 5G 路由器的，可能出错
