### ISSUE TITLE
不支持esp-idf v4.2?

### ISSUE THREAD

**Issue by guo652917087** [EspressifApp/EspBlufiForAndroid#20]
我测试了esp-idf v4.0版本可以，v4.1和v4.2不行。报错：BLUFI_EXAMPLE: blufi_dh_negotiate_data_handler make public failed -12416。定位到dhm_check_range( &ctx->GY, &ctx->P ) 不符合。ios也一样不支持4.1和4.2版本。

**Comment by XuXiangJun** [comment]
这个问题可以去 https://github.com/espressif/esp-idf 项目下提出

**Comment by guo652917087** [comment]
ok
