### ISSUE TITLE
协商秘钥接口异常

### ISSUE THREAD

**Issue by pdw0204** [EspressifApp/EspBlufiForAndroid#32]
运行demo
app版本：1.6.3
blufi库版本： 2.3.7

手机环境
机型：华为nova 2s
系统rom: 鸿蒙2.0.0

芯片型号
eps32 s3

蓝牙链接上后，进行加密协商，返回错误码-4000
![20220706152525](https://user-images.githubusercontent.com/1525744/177493685-9d3824a9-c9c0-4656-87be-240de3b267c7.jpg)

望解决

**Comment by pdw0204** [comment]
芯片型号是eps32 s3

**Comment by XuXiangJun** [comment]
请问您的 idf 版本是多少？

**Comment by pdw0204** [comment]
idf版本是4.4， 现在就是发现有些机型上协商加密的接口会出现错误。

**Comment by XuXiangJun** [comment]
> idf版本是4.4， 现在就是发现有些机型上协商加密的接口会出现错误。
> 详细版本号：ESP-IDF v4.4-263-g000d3823bb-dirty

能提供一下具体的 commit id 吗？

我这边使用 idf  branch release/v4.4 最新代码
手机为华为 mate40pro, 系统为鸿蒙 2.0
芯片 esp32s3
使用下来并没有出现这个问题

**Comment by XuXiangJun** [comment]
还有一个可能
-4000 是 Gatt 写超时错误码，当前 APP 设置的超时时间是 5 秒
有可能是您的手机的 BLE 性能的问题导致数据没有在 5 秒内写完
因此可以尝试一下增加超时时间，超时参数在类 `BlufiConstants` 内，`GATT_WRITE_TIMEOUT` 改为 15000 或者 20000 试试

**Comment by pdw0204** [comment]
> 

有时候超时后onCharacteristicWrite回调的status=133

**Comment by pdw0204** [comment]
我调试了下，默认的包大小就是20
![Uploading 20220707150957.jpg…]()

**Comment by XuXiangJun** [comment]
> 我调试了下，默认的包大小就是20 

默认值为20，那有可能是 MTU 设置都没有成功
但是我看你最上面的截图， MTU 设置是成功了的，那么在不主动设置分包的情况下，默认分包大小应该是 512 - 4 才是啊

**Comment by XuXiangJun** [comment]
> 我的另外一台鸿蒙系统手机（mate 20 pro）也没问题，很奇怪。 发送第一部分数据帧进行秘钥协商很快就过去了，是发送第二部分的设置安全模式数据超时了，可能是数据比较长。但我发送自定义数据超过一定长度后也是超时。我现在试的超时时间是60s，第二部分数据长度是267个字节。
> 
> 另外BlufiClientImpl.DH_P字段值是否可用自定义短一些，以减少传输数据？
> 
> ![超时数据](https://user-images.githubusercontent.com/1525744/177519077-0fdfb68c-eadd-4b13-9f6d-729cfbe0102d.jpg)

从这张截图看
很明显分包远远大于20啊

**Comment by pdw0204** [comment]
设置小点就可以了，应该是手机的蓝牙芯片性能问题，谢谢解答。
