### ISSUE TITLE
ArrayIndexOutOfBoundsException BlufiClientImpl.parseNotification(BlufiClientImpl.java:476)

### ISSUE THREAD

**Issue by leonhomedigy** [EspressifApp/EspBlufiForAndroid#33]
lib-blufi-android: `2.3.7`
Android version:9
Device: ONEPLUS A5000

This happens when I call `requestDeviceStatus` in `onPostConfigureParams`.  
The weird thing is this only happens if I pass in a valid SSID/pwd pair.  Invalid pair would trigger `onDeviceStatusResponse` as expected.  

This doesn't happen if I set it through the EspBlufiForAndroid app.   

Any hint would be greatly appreciated.  

Here is the error
> W/System.err(25997): java.lang.ArrayIndexOutOfBoundsException: src.length=20 srcPos=4 dst.length=19 dstPos=0 length=19
W/System.err(25997): 	at java.lang.System.arraycopy(Native Method)
W/System.err(25997): 	at blufi.espressif.BlufiClientImpl.parseNotification(BlufiClientImpl.java:476)
W/System.err(25997): 	at blufi.espressif.BlufiClientImpl.access$2100(BlufiClientImpl.java:45)
W/System.err(25997): 	at blufi.espressif.BlufiClientImpl$InnerGattCallback.onCharacteristicChanged(BlufiClientImpl.java:1257)
W/System.err(25997): 	at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:468)
W/System.err(25997): 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:770)
W/System.err(25997): 	at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:39)
W/System.err(25997): 	at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:462)
W/System.err(25997): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:185)
W/System.err(25997): 	at android.os.Binder.execTransact(Binder.java:752)

Here is the log from ESPIDF running the BLUFI_EXAMPLE:
> I (17765106) BLUFI_EXAMPLE: BLUFI get wifi status from AP
W (17765106) BT_GATT: attribute value too long, to be truncated to 20
I (17766186) BLUFI_EXAMPLE: BLUFI ble disconnect
I (17766686) esp_netif_handlers: sta ip: 192.168.0.12, mask: 255.255.255.0, gw: 192.168.0.1
I (17766686) BLUFI_EXAMPLE: BLUFI BLE is not connected yet

**Comment by XuXiangJun** [comment]
In fact,
 if you post the `configure` data successfully,
 whether the result is successful or not, the device will return the status,
 so you just need to wait for the callback `onDeviceStatusResponse`

**Comment by leonhomedigy** [comment]
Thanks!  Just noticed I'm using a version that is way back.  Ran it again with esp 4.3.3 and everything is working.  Closing this issue.
