### ISSUE TITLE
发送蓝牙消息是通过哪个方法，有没有直接蓝牙通信的手机端代码案例

### ISSUE THREAD

**Issue by tomsean** [EspressifApp/EspBlufiForAndroid#6]

**Comment by EspressifApp** [comment]
Blufi配网流程代码可参考类 BlufiConfigureActivity的内部类 Task
BLE连接和断开我们封装了一个类 EspBleHelper
Blufi通信相关的API使用建立类BlufiCommunicator来调用，这部分代码暂时还不开放

**Comment by tomsean** [comment]
BlufiCommunicator  通信相关的应该要开放出来，例如我需要通过蓝牙重启wifi模块等
