### ISSUE TITLE
请问一下app端在局域网如何获取8266设备的mac地址

### ISSUE THREAD

**Issue by NamedJack** [EspressifApp/EspBlufiForAndroid#8]
我查看sdk文档内说明 在局域网内向1025端口发送消息 如果8266连接上wifi就会返回mac地址和ip地址 但是我并没有收到消息，请问向局域网的 哪个端口发送什么消息才能收到mac地址和ip的返回

**Comment by XuXiangJun** [comment]
8266的话往1025端口发送广播  "Are You Espressif IOT Smart Device?" 不含引号
设备收到广播后就会回复mac地址等信息了

**Comment by XuXiangJun** [comment]
发送的是UDP广播
设备会往你建立的udp socket回复消息

**Comment by NamedJack** [comment]
好的 谢谢
