### ISSUE TITLE
调用negotiateSecurity方法协商加密时，有时会报错

### ISSUE THREAD

**Issue by Vickshine** [EspressifApp/EspBlufiForAndroid#9]
调用negotiateSecurity方法协商加密时，有时会报错， __negotiateSecurity()中    devicePublicKey = mDevicePublicKeyQueue.take();  这行有时会catch

**Comment by EspressifApp** [comment]
有 log 吗？
这句只会 catch InterruptedException, 是不是有其他地方调了close() ?

**Comment by Vickshine** [comment]
我是在onServicesDiscovered中    boolean requestMtu = gatt.requestMtu(MTU); 接收到onMtuChanged 事件后，    开始协商加密negotiateSecurity()，偶尔就会在 devicePublicKey = mDevicePublicKeyQueue.take();出错抛异常InterruptedException

**Comment by XuXiangJun** [comment]
请问现在还会有这个问题吗
